name: "infer_bls"
backend: "python"
max_batch_size: 8

parameters [
  {
    key: "engine_dir"
    value: { string_value: "/workspace/whisper-medium-tllm"}
  }
]

input [
  {
    name: "TEXT_PREFIX"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "WAV"
    data_type: TYPE_FP32
    dims: [-1]
  },
  {
    name: "WAV_LENS"
    data_type: TYPE_INT32
    dims: [1]
    optional: True
  },
  {
    name: "MAX_NEW_TOKENS"
    data_type: TYPE_INT32
    dims: [1]
    optional: True
  }
]

output [
  {
    name: "TRANSCRIPTS"
    data_type: TYPE_STRING
    dims: [1]
  }
]

dynamic_batching {
    max_queue_delay_microseconds: 100
  }
instance_group [
    {
      count: 4
      kind: KIND_CPU
    }
  ]