FROM nvcr.io/nvidia/tritonserver:24.09-trtllm-python-py3
RUN python3 -m pip install tensorrt-llm==0.15.0.dev2024101500

WORKDIR /workspace
COPY requirements.txt .
COPY prepare.sh .
COPY launch_triton_server.py .
COPY fill_template.py .

RUN python3 -m pip install -r requirements.txt